### ISSUE TITLE
 AttributeError: module 'enum' has no attribute 'IntFlag'

### ISSUE THREAD

**Issue by xunhanliu** [cardiffnlp/tweetnlp#4]
Traceback (most recent call last):
    File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.6/site-packages/pip/__main__.py", line 27, in <module>
      "ignore", category=DeprecationWarning, module=".*packaging\\.version"
    File "/usr/lib64/python3.6/warnings.py", line 131, in filterwarnings
      import re
    File "/usr/lib64/python3.6/re.py", line 142, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------

**Comment by xunhanliu** [comment]
>>> pip uninstall enum34
